version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"
    groups:
      markuplint:
        patterns:
          - "@markuplint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"
